version: '3'

services:
  app:
    image: allanlee0724/test:v4
    container_name: planetarium
    ports:
      - 8080:8080
    environment:
      - VARIABLE=VALUE
    volumes:
      - ./logs/:/logs/
  
  loki:
    image: grafana/loki:latest
    container_name: loki-logging
    ports:
      - 3100:3100

  promtail:
    image: grafana/promtail:latest
    container_name: promtail-logging
    volumes:
      - ./configs/promtail-config.yml:/etc/promtail/promtail-config.yml
      - ./logs/rollingFile.log:/var/log/rollingFile.log
    command: "--config.file=/etc/promtail/promtail-config.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-logging
    # volumes:
    #   - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - loki
  
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./configs/prometheus-rules.yml:/etc/prometheus/prometheus-rules.yml
      - ./configs/prometheus-config.yml:/etc/prometheus/prometheus-config.yml
    # - prometheus-data:/prometheus
    container_name: prometheus-logging
    command: "--config.file=/etc/prometheus/prometheus-config.yml"